### ISSUE TITLE
No module named `create_action`

### ISSUE THREAD

**Issue by alexroan** [Cyfrin/audit-repo-cloner#2]
```
Traceback (most recent call last):
  File "/Users/alexroan/Documents/Tools/audit-repo-cloner/venv/bin/audit_repo_cloner", line 5, in <module>
    from audit_repo_cloner import create_audit_repo
  File "/Users/alexroan/Documents/Tools/audit-repo-cloner/audit_repo_cloner/__init__.py", line 2, in <module>
    from .create_audit_repo import create_audit_repo
  File "/Users/alexroan/Documents/Tools/audit-repo-cloner/audit_repo_cloner/create_audit_repo.py", line 7, in <module>
    from create_action import create_action
ModuleNotFoundError: No module named 'create_action'
```

**Comment by giovannidisiena** [comment]
Fixed by #20.
